apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chat-app
type: Opaque
stringData:
  jwt: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTc2NzA1MzM3MCwiaWF0IjoxNzY3MDUzMzcwfQ.NckZ_Y2lcskDyUIZuF_U5dGCnkPoSDpcRFtcrsXWl9s

